### ISSUE TITLE
Multi-select for writing to an itemdesc file.

### ISSUE THREAD

**Issue by Admin-Yukiko** [polserver/poltools#4]
The "plugin test" plugin gives an option when you right-click on an art tile graphic to export that graphic's info to an itemdesc.cfg file but you can only export one item at a time. Would it be possible to select multiple items by <control> left-clicking on each graphic and then right-clicking on one of the selected items and choosing "Create itemdesc entry" thus having all of the selected items entered in an itemdesc.cfg file? Adding items one at a time is not a serious inconvenience because it does append each new item to the itemdesc file but the ability to select multiple items and right-click just once to write them to a file would save some mouse clicks.

**Comment by AsYlum-** [comment]
I'm on it :)
